version: '3'

services:
  dataflow-mysql:
    image: mysql:5.7.25
    container_name: dataflow-mysql
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307

  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-lucas:${DATAFLOW_VERSION:-2.8.1}
    container_name: dataflow-server
    ports:
      - "9393:9393"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dataflow-mysql:3307/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver

      - SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI=${SKIPPER_URI:-http://skipper-server:7577}/api

      - SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED=true
      - SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED=true

      - SPRING_CLOUD_DATAFLOW_SCHEDULER_URL=http://dataflow-scheduler:8080
      - SPRING_CLOUD_KUBERNETES_ENABLED=false
      - SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED=false

    restart: always
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/home/cnb/scdf}
      - ./tasks/:/tasks/
    depends_on:
      - dataflow-mysql

  dataflow-scheduler:
    image: springcloud/dataflow-scheduler:0.0.1-SNAPSHOT
    container_name: dataflow-scheduler
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_DATA_FLOW_URL=http://dataflow-server:9393

      - SPRING_DATASOURCE_URL=jdbc:h2:mem:scheduler
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=''

