logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/quartz_tables_h2.sql


scdf:
  url: ${SPRING_CLOUD_DATA_FLOW_URL}

