spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dataflow
    username: root
    password: rootpw
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    dataflow:
      features:
        schedules-enabled: true
      scheduler:
        url: http://localhost:8080
    kubernetes:
      enabled: false

